"""first

Revision ID: 2e68415c5b0f
Revises: 
Create Date: 2025-06-27 10:30:05.633049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e68415c5b0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=300), nullable=False),
    sa.Column('channel_url', sa.String(length=350), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('configs',
    sa.Column('start_menu_text', sa.Text(length=3000), nullable=False),
    sa.Column('card_info', sa.Text(length=3000), nullable=False),
    sa.Column('support_channel_url', sa.String(length=300), nullable=False),
    sa.Column('message_to_support_text', sa.Text(length=3000), nullable=False),
    sa.Column('help_text', sa.Text(length=3000), nullable=False),
    sa.Column('rules_text', sa.Text(length=3000), nullable=False),
    sa.Column('entry_prize', sa.Integer(), nullable=False),
    sa.Column('referral_bonus', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_ban', sa.Boolean(), nullable=False),
    sa.Column('referral_active', sa.Boolean(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('deposits',
    sa.Column('factor_id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('acc_or_reject_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acc_or_reject_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposits')
    op.drop_table('users')
    op.drop_table('configs')
    op.drop_table('channels')
    # ### end Alembic commands ###
